### ISSUE TITLE
Nexor lacks PRP and doesn't provide privacy

### ISSUE THREAD

**Issue by phantomcraft** [andrewhodel/nexor#1]
Nexor lacks pseudorandom permutation and don't provide privacy as all the blocks are equal if part of plaintext are constant.

Easy to reproduce:

Get zeroes from /dev/zero:

```
user@localhost:/dev/shm$ dd if=/dev/zero of=./plaintext count=1024 bs=1
1024+0 records in
1024+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.00113437 s, 903 kB/s
```

Generate 2 keys:

```
user@localhost:/dev/shm$ ./nexor genkey ./key 2
2 keys written to ./key
```

Encrypt:

`user@localhost:/dev/shm$ ./nexor enc ./key ./plaintext ./ciphertext`

Open the ciphertext with a hexadecimal editor:

![Screenshot from 2021-06-13 22-00-04](https://user-images.githubusercontent.com/39815480/121830729-3416fa00-ccb5-11eb-9be7-5f85adaf7dba.png)

/\ The first 16 bytes are the random block, the rest are the ciphertext, all the 16 byte blocks are the same.

This could lead to a privacy leak as ECB does: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_codebook_(ECB)

The solution would be implementing a pseudo-random function in Nexor and turn it in a true block cipher. Of course, the pseudo-random permutation should be strong enough according to the key size. Together with CBC mode or XTS could provide a block cipher with unlimited key size, remembering that there is no cipher with unlimited key sizes.

A more interesting idea would be implement a tweaked mode of operation, in which a secondary key can change the permutation of cipher for each block.

**Comment by andrewhodel** [comment]
In the README:

```
Servers and clients must use the random block for proper security.
When a socket is opened and for the duration of that socket being open
each end must store each (validly decrypted) requests random block
and check that there are no repeated random blocks for the socket session
to avoid duplicate packets being sent across the wire by a hijacker.

Servers must also on connection open generate a login hash and send it to the client.
Then the client must include that login hash when it sends the actual login credentials.
The server would then have the hash in memory and be able to validate the login request
which stops it from being repeated.  If someone were to wirejack the login request it would not
be reusable due to the hash being generated by the server.
```

You aren't using a random block for each transmission, nor are you using a login hash.

**Comment by andrewhodel** [comment]
@phantomcraft here's how in code:

[sec-socket-example-node-and-c.zip](https://github.com/andrewhodel/nexor/files/6645374/sec-socket-example-node-and-c.zip)

**Comment by andrewhodel** [comment]
Otherwise are you just trying to say sending nothing, and the same random block over and over sends the same xor'd data of the same 16 bytes?

Obviously!

**Comment by andrewhodel** [comment]
In other words, send a checksum back and forth that’s recalulated each time in the message so it can never be length 0 like you are showing. 

I don’t understand why terms like PRP would be made up. 



Thank You,
Andrew Hodel
